### PR TITLE
ci: update terraform definitions to the latest ones

### PR DESCRIPTION
**Pull request by ondrejbudai**
Changes:
- Fedora 37 no longer requires any hacks
- All the images deleted by cloud-cleaner are back:
  - Centos Stream 9
  - All RHEL nightlies
- Instances shouldn't be killed as much anymore

### CODE REVIEW

**Comment by jabia99** [comment]
Just FYI: Please ignore "aws" and "azure" jobs in CI. The only relevant ones right now are "IB-aws" and "IB-azure"

**Comment by ondrejbudai** [comment]
azure passed though, is that bad? :stuck_out_tongue_winking_eye:

**Comment by jabia99** [comment]
We are waiting until we can find what images we should test against. (As Alex would say, the latest and greatest). So for now we just ignore those tests. :)

Once a PR is merged, only IB tests run. If these pass, `prod` container image is updated

**Comment by jabia99** [comment]
Thanks Ondrej, highly appreciate this :heart:

**Pull request merged**
