### PR TITLE
ci: add tags to AWS instances

### PR DESCRIPTION
**Pull request by lavocatt**
The new terraform runners support an extended lists of tags to get a greater precision on the stats we can extract from AWS cost center.

### CODE REVIEW

**Comment by jabia99** [comment]
(Please ignore "aws" and "azure" jobs in CI. The only relevant ones right now are "IB-aws" and "IB-azure")

CI gets an error when trying to deploy fedora37 runners.

**Comment by jabia99** [comment]
Can you please update the commit to `79e0bf92fa92a143a703acc795d4c9cfc8001e66` ? We need the new updates to be able to deploy runners

**Comment by jabia99** [comment]
This PR should solve the issue with fedora 37 runners: https://github.com/osbuild/gitlab-ci-terraform/pull/83

**Comment by ondrejbudai** [comment]
Surpassed by #163

**Pull request closed without merging**
