### PR TITLE
Fixed version comparisons in all the test suites and conftest.py

### PR DESCRIPTION
**Pull request by narmaku**
Before we were comparing floats, but it turns out that it is not accurate, since in the case of RHEL 8.10, it is semantically greater than e.g. 8.4, however if they are compared as float, 8.4 is greater than 8.10.

### CODE REVIEW

**Review by jrusz — APPROVED** [review]
LGTM! Let's see if CI agrees :) ...  Do you want me to test it in osbuild-composer test suite as well? It's just a matter of changing the CIV image tag, righ?

**Comment by narmaku** [comment]
> LGTM! Let's see if CI agrees :) ... Do you want me to test it in osbuild-composer test suite as well? It's just a matter of changing the CIV image tag, righ?

Thanks @jrusz ! Yes, that would be great, so we can confirm that this also solves the issues with RHEL-8.10.
Exactly, you can use this PR as the tag (pr-286), instead of "prod" here:

- https://github.com/osbuild/osbuild-composer/blob/3fe36d00120d69907677b5a922650a14ff235ebd/test/cases/aws.sh#L223

**Comment by jrusz** [comment]
It passed on both 9.4 and 8.10! https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/1063680945

**Review by sshmulev — COMMENTED** [review]
I would try to keep on a consistent argument  when comparing the versions:
right now I see 'rhel_version', 'product_version', 'version.parse(host.system_info.release)', 'product_release_version', maybe lets choose one argument for all these comparisons?

**Comment by narmaku** [comment]
> I would try to keep on a consistent argument name when comparing the versions: right now I see 'rhel_version', 'product_version', 'version.parse(host.system_info.release)', 'product_release_version', maybe lets choose one argument for all these comparisons?

Good point. Maybe we can choose a generic one, like `system_release`. What do you think?

**Pull request merged**
